name: import_existing_certificate
label: 3E. Import a pkcs12 file

description: |
  Import pkcs12 certificate to PAN-OS

type: python3

extends:

labels:
  collection:  
    - Authentication Policy
    - X509

variables:
  - name: TARGET_IP
    description: Host
    default: 127.0.0.1
    type_hint: ip_address
  - name: api_key
    description: API Key
    default: abc123
    type_hint: text
  - name: CERT_NAME
    description: Certificate Label
    default: Authentication Portal
    type_hint: text 
  - name: CERT_FILE
    description: Certificate File Name
    type_hint: text
  - name: PASSPHRASE
    description: Passphrase for certificate
    type_hint: password

snippets:
  - name: import_pkcs12_certificate
    file: cert_import.py

    
