name: generate_rsa_cert
label: 3A. Generate RSA Certificate from Firewall CA

description: 
  Generate RSA Certificate from On Box CA

type: rest

extends:

labels:
  collection:  
    - Authentication Policy
    - X509
    
variables:
  - name: TARGET_IP
    description: Host
    default: 127.0.0.1
    type_hint: ip_address
  - name: api_key
    description: API Key
    default: abc123
    type_hint: text
  - name: CERT_NAME
    description: Certificate Label
    default: Authentication Portal
    type_hint: text 
  - name: CERT_HOSTNAME
    description: FQDN for certficate
    default: auth.customer.com
    type_hint: text  
  - name: CERT_NBITS
    description: Certificate Bits
    default: 2048
    type_hint: dropdown
    dd_list:
      - key: 2048
        value: 2048
      - key: 3072
        value: 3072
      - key: 4096
        value: 4096
  - name: CERT_DIGEST
    description: Certificate Digest
    default: SHA512
    type_hint: dropdown
    dd_list:
      - key: SHA256
        value: SHA256
      - key: SHA384
        value: SHA384
      - key: SHA512
        value: SHA512     
  - name: CA_CERT_NAME
    description: On-Box Signing CA
    default: Demo CA
    type_hint: text   

snippets:
  - name: generate_cert
    path: https://{{ TARGET_IP }}/api/?type=op&cmd=<request><certificate><generate><certificate-name>{{ CERT_NAME }}</certificate-name><name>{{ CERT_HOSTNAME }}</name><algorithm><RSA><rsa-nbits>{{ CERT_NBITS }}</rsa-nbits></RSA></algorithm><digest>{{ CERT_DIGEST }}</digest><ca>no</ca><hostname><member>{{ CERT_HOSTNAME }}</member></hostname><signed-by>{{ CA_CERT_NAME }}</signed-by></generate></certificate></request>&key={{ api_key }}
    #path: https://{{ TARGET_IP }}/api/?type=op&cmd=<request><certificate><generate><hostname><member>test.customer.com</member></hostname><days-till-expiry>365</days-till-expiry><signed-by>Demo CA2</signed-by><certificate-name>Test Cert</certificate-name><name>test.customre.com</name><algorithm><RSA><rsa-nbits>2048</rsa-nbits></RSA></algorithm></generate></certificate></request></operations></request>&key={{ api_key }}
    output_type: xml
    outputs:
      - name: result
        capture_pattern: result
  - name: generate_ssltls_profile
    path: https://{{ TARGET_IP }}/api?key={{ api_key }}&type=config&action=set&xpath=/config/shared/ssl-tls-service-profile/entry[@name='{{ CERT_NAME }} - Skillet']&element=<protocol-settings><min-version>tls1-2</min-version><max-version>max</max-version></protocol-settings><certificate>{{ CERT_NAME }}</certificate>
    output_type: xml
    outputs:
      - name: result
        capture_pattern: result

