name: create_ca
label: 2A. Generate RSA CA on Firewall

description: |
  Create CA on Firewall. RSA4096 / SHA512

type: rest

extends:

labels:
  collection:  
    - Authentication Policy
    - X509

variables:
  - name: TARGET_IP
    description: Host
    default: 127.0.0.1
    type_hint: ip_address
  - name: api_key
    description: API Key
    default: abc123
    type_hint: text
  - name: CA_CERT_NAME
    description: Certificate Authority Name
    default: Demo CA
    type_hint: text 
  - name: CA_DESCRIPTION
    description: CA Description
    default: Demo Root CA
    type_hint: text  
  - name: CA_ORG
    description: Organization (Company)
    default: Demo Company
    type_hint: text 
  - name: CA_COUNTRY
    description: Organization Country Code
    default: US
    type_hint: text 
  - name: CA_STATE
    description: Organization State
    default: CA
    type_hint: text      
  - name: CA_LOCAL
    description: Organization Locality
    default: Santa Clara
    type_hint: text 
  - name: CA_EMAIL
    description: Certificate Contact Email
    default: demo@customer.com
    type_hint: text

snippets:
  - name: generate_ca
    path: https://{{ TARGET_IP }}/api/?type=op&cmd=<request><certificate><generate><ca>yes</ca><country-code>{{ CA_COUNTRY }}</country-code><days-till-expiry>3650</days-till-expiry><digest>sha512</digest><email>{{ CA_EMAIL }}</email><locality>{{ CA_LOCAL }}</locality><organization>{{ CA_ORG }}</organization><state>{{ CA_STATE }}</state><algorithm><RSA><rsa-nbits>4096</rsa-nbits></RSA></algorithm><certificate-name>{{ CA_CERT_NAME }}</certificate-name><name>{{ CA_DESCRIPTION }}</name></generate></certificate></request>&key={{ api_key }}
    output_type: xml
    outputs:
      - name: result
        capture_pattern: result
