name: generate_api_key
label: 1. Generate PAN-OS API Key

description: |
  Generate a PAN-OS API Key. Required if an API key is not available for later steps. 

type: rest

extends:

labels:
  collection:
    - Authentication Policy
    - X509
    
variables:
  - name: TARGET_IP
    description: Host
    default: 127.0.0.1
    type_hint: ip
  - name: TARGET_USERNAME
    description: Username
    default: admin
    type_hint: text
  - name: TARGET_PASSWORD
    description: Password
    default: admin
    type_hint: password


snippets:
  - name: key_gen
    path: https://{{ TARGET_IP }}/api/?type=keygen&user={{ TARGET_USERNAME }}&password={{ TARGET_PASSWORD }}
    # this should output capturing which will set a variable called 'api_key' in the workflow, which can be referenced
    # in a skillet called after this one, any variable with a name called api_key will be prepopulated with the
    # value that is captured from the output of this xml api command
    output_type: xml
    outputs:
      - name: api_key
        capture_pattern: result/key
